name: "changelog"
description: "Blazing fast dev micro blogging"
inputs:
  title:
    description: "Title of your site"
    required: false
    default: "Forkoff"
  description:
    description: "Description for your changelog"
    required: false
    default: "Blazing fast micro blogging"
  base:
    description: "Base URL path"
    required: false
    default: ${{ github.repository }}
  owner:
    description: "Repository owner"
    required: false
    default: ${{ github.repository_owner }}
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TITLE: ${{ inputs.title }}
    DESCRIPTION: ${{ inputs.description }}
    BASE: ${{ inputs.base }}
    OWNER: ${{ inputs.owner }}
