name: "changelog"
description: "Blazing fast dev micro blogging"
inputs:
  title:
    description: "Title of your changelog"
    required: false
    default: "Changelog"
  description:
    description: "Description for your changelog"
    required: false
    default: "Blazing fast micro blogging"
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/configure-pages@v5
      with:
        static_site_generator: next
    - uses: actions/cache@v4
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-next-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-next-${{ hashFiles('**/bun.lockb') }}-
    - run: ls -la
      shell: bash
    - run: bun install
      shell: bash
    - run: bun run build
      shell: bash
      env:
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_DESCRIPTION: ${{ inputs.title }}
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./out
