name: "changelog"
description: "Blazing fast dev micro blogging"
inputs:
  title:
    description: "Title of your changelog"
    required: false
    default: "Changelog"
  description:
    description: "Description for your changelog"
    required: false
    default: "Blazing fast micro blogging"
  base_path:
    description: "Base URL path"
    required: false
    default: ${{ github.repository }}
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TITLE: ${{ inputs.title }}
    DESCRIPTION: ${{ inputs.description }}
    BASE_PATH: ${{ inputs.base_path }}
