name: "changelog"
description: "Blazing fast dev micro blogging"
inputs:
  title:
    description: "Title of your changelog"
    required: false
    default: "Changelog"
  description:
    description: "Description for your changelog"
    required: false
    default: "Blazing fast micro blogging"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.title }}"
    - "${{ inputs.description }}"
