name: "changelog"
description: "Blazing fast dev micro blogging"
inputs:
  title:
    description: "Title of your changelog"
    required: false
    default: "Changelog"
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_TITLE" > hello.txt
      shell: bash
      env:
        INPUT_TITLE: ${{ inputs.title }}
    - uses: actions/upload-artifact@v4
      with:
        path: hello.txt
