on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          title: Changelog
          description: Blazing fast micro blogging

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
