on: push

permissions:
  pages: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          title: Changelog
          description: Blazing fast micro blogging
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ github.workspace }}/artifact.zip

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
